// main actions
export const UPDATE_DATA = 'UPDATE_DATA';

// scene actions
export const ADD_SCENE_COMPONENT = 'ADD_SCENE_COMPONENT';
export const REMOVE_SCENE_COMPONENT = 'REMOVE_SCENE_COMPONENT';
export const UPDATE_SCENE_COMPONENT = 'UPDATE_SCENE_COMPONENT';